In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
credit_risk=pd.read_csv(r"C:\Users\dwipa\Desktop\pd_model_development\input\credit_risk_dataset.csv")
credit_risk_copy=credit_risk.copy()

credit_risk.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

### Exploratory Data Analysis

In [3]:
credit_risk.shape

(32581, 12)

In [4]:
credit_risk.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

The max age and max employment length seem to be off the charts and clearly point to data error. Will delete.

In [5]:
# credit_risk.pivot_table(index='person_age', columns='loan_status', 
                        # values='person_income', aggfunc='count').reset_index().sort_values(by='person_age', ascending=False)

Two points to note, it is highly unusual for a person to be alive beyond 100 years, and someone to take a loan beyond the age of 70-80 years. So deleteing the records beyond the age of 70 seems feasible.

In [6]:
cr_age_rmvd=credit_risk[credit_risk['person_age']<=70]

In [7]:
cr_age_rmvd.reset_index(drop=True, inplace=True)
cr_age_rmvd.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [8]:
cr_age_rmvd.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32568.000000,3.256800e+04,31673.000000,32568.000000,29455.000000,32568.000000,32568.000000,32568.000000
mean,27.705478,6.588414e+04,4.788179,9589.756817,11.011899,0.218251,0.170223,5.799282
std,6.152804,5.254017e+04,4.136668,6322.238005,3.240722,0.413065,0.106783,4.043135
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,70.000000,2.039784e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [9]:
cr_age_rmvd.isna().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3113
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [10]:
# cr_age_rmvd.groupby(['person_emp_length']).count()

In [11]:
# cr_age_rmvd.pivot_table(index='person_emp_length', 
#                         columns='loan_status', values='person_income', 
#                         aggfunc='count').reset_index().sort_values(by='person_emp_length', ascending=False)

In [12]:
# removing employment length greater than 42 because I am taking 60 to be the retirement 
# age and if a person starts working from 18 yo then he can serve 42 years

# For some reason, when we remove basis on this criteria, the missing values from the dataset also gets removed. 
emp_ln_rmvd=cr_age_rmvd[cr_age_rmvd['person_emp_length']<42]

emp_ln_rmvd.reset_index(drop=True, inplace=True)
emp_ln_rmvd.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2

In [13]:
emp_ln_rmvd.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,31671.000000,3.167100e+04,31671.000000,31671.000000,28626.000000,31671.000000,31671.000000,31671.000000
mean,27.717754,6.649231e+04,4.780714,9660.637492,11.040070,0.215497,0.169621,5.804395
std,6.159859,5.277413e+04,4.028718,6334.716643,3.229507,0.411173,0.106275,4.048776
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.936600e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.600000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,8.000000e+04,7.000000,12500.000000,13.480000,0.000000,0.230000,8.000000
max,70.000000,2.039784e+06,38.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [14]:
credit_risk.shape[0]-emp_ln_rmvd.shape[0]

910

In [15]:
cr_data=emp_ln_rmvd.copy()
cr_data.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length                0
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3045
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

Loan interest rate has a similar mean and median. Imputing the missing values in loan_int_rate with mean

In [16]:
cr_data['loan_int_rate']=cr_data['loan_int_rate'].fillna(cr_data['loan_int_rate'].median())

In [17]:
cr_data.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,31671.000000,3.167100e+04,31671.000000,31671.000000,31671.000000,31671.000000,31671.000000,31671.000000
mean,27.717754,6.649231e+04,4.780714,9660.637492,11.035256,0.215497,0.169621,5.804395
std,6.159859,5.277413e+04,4.028718,6334.716643,3.070364,0.411173,0.106275,4.048776
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.936600e+04,2.000000,5000.000000,8.490000,0.000000,0.090000,3.000000
50%,26.000000,5.600000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,8.000000e+04,7.000000,12500.000000,13.160000,0.000000,0.230000,8.000000
max,70.000000,2.039784e+06,38.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [18]:
cr_data.groupby('loan_status').count()['person_age']/cr_data.shape[0]

loan_status
0    0.784503
1    0.215497
Name: person_age, dtype: float64

In [19]:
cr_data.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2

In [20]:
cr_data.groupby('person_home_ownership').count()['loan_status']

person_home_ownership
MORTGAGE    13088
OTHER         107
OWN          2410
RENT        16066
Name: loan_status, dtype: int64

In [21]:
cr_data.groupby('loan_intent').count()['loan_status']

loan_intent
DEBTCONSOLIDATION    5064
EDUCATION            6288
HOMEIMPROVEMENT      3510
MEDICAL              5891
PERSONAL             5365
VENTURE              5553
Name: loan_status, dtype: int64

In [22]:
cr_data.pivot_table(index='loan_grade', columns='loan_status', values='loan_int_rate', aggfunc='mean')

loan_status          0          1
loan_grade
A             7.665278   7.894440
B            10.992157  11.047503
C            13.211678  13.208550
D            14.958411  14.979943
E            16.408416  16.531637
F            17.976714  17.621687
G            19.160000  19.533810

### Categorical Feature Treatment

In [23]:
cr_data_cat_treated= cr_data.copy()

In [24]:
cr_data_cat_treated.groupby('person_home_ownership').count()['loan_status']

person_home_ownership
MORTGAGE    13088
OTHER         107
OWN          2410
RENT        16066
Name: loan_status, dtype: int64

In one-hot-encoding, we usually drop one column because if all the other variables are 0 then it would mean the other column that was dropped is 1

In [25]:
person_home_ownership=pd.get_dummies(cr_data_cat_treated['person_home_ownership'], drop_first=True).astype(int)
loan_intent=pd.get_dummies(cr_data_cat_treated['loan_intent'], drop_first=True).astype(int)
cr_data_cat_treated['cb_person_default_on_file_binary']=np.where(cr_data_cat_treated['cb_person_default_on_file']=='Y', 1, 0)
loan_intent.head()

   EDUCATION  HOMEIMPROVEMENT  MEDICAL  PERSONAL  VENTURE
0          1                0        0         0        0
1          0                0        1         0        0
2          0                0        1         0        0
3          0                0        1         0        0
4          0                0        0         0        1

In [26]:
cr_data_cat_treated.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,cb_person_default_on_file_binary
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,0
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,0
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,1
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2,0

In [27]:
cr_data_to_scale=cr_data_cat_treated.drop(['person_home_ownership', 'loan_intent', 
                                           'loan_grade', 'loan_status', 'cb_person_default_on_file', 
                                           'cb_person_default_on_file_binary'], axis=1)

In [28]:
colms=cr_data_to_scale.columns
cr_data_to_scale.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
0,21,9600,5.0,1000,11.14,0.10,2
1,25,9600,1.0,5500,12.87,0.57,3
2,23,65500,4.0,35000,15.23,0.53,2
3,24,54400,8.0,35000,14.27,0.55,4
4,21,9900,2.0,2500,7.14,0.25,2

In [29]:
scaler=StandardScaler()

In [30]:
scaled_df=pd.DataFrame(scaler.fit_transform(cr_data_to_scale), columns=colms)
scaled_df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
count,3.167100e+04,3.167100e+04,3.167100e+04,3.167100e+04,3.167100e+04,3.167100e+04,3.167100e+04
mean,-5.743391e-17,1.435848e-17,1.435848e-17,-7.179239e-17,2.149285e-16,-2.261460e-16,-1.148678e-16
std,1.000016e+00,1.000016e+00,1.000016e+00,1.000016e+00,1.000016e+00,1.000016e+00,1.000016e+00
min,-1.252931e+00,-1.184165e+00,-1.186678e+00,-1.446123e+00,-1.828885e+00,-1.596086e+00,-9.396557e-01
25%,-7.658989e-01,-5.140158e-01,-6.902340e-01,-7.357410e-01,-8.289883e-01,-7.492103e-01,-6.926635e-01
50%,-2.788670e-01,-1.988185e-01,-1.937903e-01,-2.621528e-01,-1.473982e-02,-1.846264e-01,-4.456714e-01
75%,3.705088e-01,2.559570e-01,5.508752e-01,4.482296e-01,6.920278e-01,5.681522e-01,5.422971e-01
max,6.864267e+00,3.739186e+01,8.245753e+00,4.000141e+00,3.968564e+00,6.213992e+00,5.976124e+00

In [31]:
scaled_combined=pd.concat([scaled_df,person_home_ownership, loan_intent],axis=1)
scaled_combined['cb_person_default_on_file']=cr_data_cat_treated['cb_person_default_on_file_binary']
scaled_combined['loan_status']=cr_data_cat_treated['loan_status']
scaled_combined.head()

# not bringing back loan grade

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,OTHER,OWN,RENT,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE,cb_person_default_on_file,loan_status
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0,0,1
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0,0,1
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0,1,1
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1,0,1

In [32]:
scaled_combined.shape

(31671, 17)

In [33]:
scaled_combined.groupby('loan_status').count().person_age

loan_status
0    24846
1     6825
Name: person_age, dtype: int64

In [34]:
target=scaled_combined['loan_status']
features=scaled_combined.drop('loan_status', axis=1)
features.head()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,OTHER,OWN,RENT,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE,cb_person_default_on_file
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0,0
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0,0
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0,1
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1,0

There is a high imbalance in the data. So we need to balance the data. We will use smote technique to balance the data

### SMOTE Synthetic Minority Oversampling Technique

In [35]:
# pip install imbalanced-Learn

In [36]:
from imblearn.over_sampling import SMOTE

In [37]:
smote=SMOTE()

In [38]:
balanced_features, balanced_target=smote.fit_resample(features, target)

In [39]:
# all_data=balanced_features.copy()
# all_data['loan_status']=balanced_target
# all_data.groupby('loan_status').count().person_age

#### Models Training

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from xgboost import XGBClassifier

In [42]:
X_train, X_test, y_train, y_test=train_test_split(balanced_features, balanced_target, test_size=0.2, random_state=42)

In [43]:
y_test.shape

(9939,)

In [104]:
logit=LogisticRegression()
logit.fit(X_train, y_train)

LogisticRegression()

In [106]:
import pickle

In [108]:
with open('LogisticPDModel.pkl', 'wb') as file:
    pickle.dump(logit, file)

In [45]:
logit.score(X_train, y_train)

0.7825321359394259

In [46]:
y_pred_logit=logit.predict(X_test)

In [47]:
print(classification_report(y_test, y_pred_logit))

              precision    recall  f1-score   support

           0       0.78      0.78      0.78      4995
           1       0.78      0.78      0.78      4944

    accuracy                           0.78      9939
   macro avg       0.78      0.78      0.78      9939
weighted avg       0.78      0.78      0.78      9939

In [64]:
def feature_importance_mapping(model, features):
    feature_imp=pd.DataFrame({'features':features.columns, 'coeff':model.coef_[0]})
    feature_imp.sort_values(by='coeff', ascending=False, inplace=True)
    display(feature_imp)
feature_imp_logit=pd.DataFrame({'features':balanced_features.columns, 'coeff_logit':logit.coef_[0]})
feature_importance_mapping(logit, balanced_features)

                      features     coeff
5          loan_percent_income  1.395252
4                loan_int_rate  0.989437
9                         RENT  0.464900
15   cb_person_default_on_file  0.066307
1                person_income  0.057039
6   cb_person_cred_hist_length  0.021204
2            person_emp_length -0.031978
0                   person_age -0.081021
11             HOMEIMPROVEMENT -0.308789
12                     MEDICAL -0.556714
3                    loan_amnt -0.665658
7                        OTHER -0.833533
13                    PERSONAL -0.985018
10                   EDUCATION -1.246159
14                     VENTURE -1.527150
8                          OWN -2.129313

### Random Forest Classifier

In [49]:
rf=RandomForestClassifier()

In [50]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [109]:
with open('RandomForestPDModel.pkl', 'wb') as file:
    pickle.dump(rf, file)

In [51]:
y_pred_rf=rf.predict(X_test)

In [52]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.91      0.97      0.94      4995
           1       0.97      0.91      0.94      4944

    accuracy                           0.94      9939
   macro avg       0.94      0.94      0.94      9939
weighted avg       0.94      0.94      0.94      9939

In [66]:
def feature_importance_mapping2(model, features):
    feature_imp=pd.DataFrame({'features':features.columns, 'coeff':model.feature_importances_})
    feature_imp.sort_values(by='coeff', ascending=False, inplace=True)
    display(feature_imp)
feature_imp_rf=pd.DataFrame({'features':balanced_features.columns, 'coeff_rr':rf.feature_importances_})
feature_importance_mapping2(rf, balanced_features)

                      features     coeff
5          loan_percent_income  0.206761
4                loan_int_rate  0.206094
1                person_income  0.152256
3                    loan_amnt  0.081368
2            person_emp_length  0.074098
0                   person_age  0.061891
6   cb_person_cred_hist_length  0.057276
9                         RENT  0.051025
8                          OWN  0.019812
11             HOMEIMPROVEMENT  0.017837
14                     VENTURE  0.017365
15   cb_person_default_on_file  0.016735
10                   EDUCATION  0.015288
13                    PERSONAL  0.013159
12                     MEDICAL  0.008611
7                        OTHER  0.000423

#### XGBoost Model

In [54]:
xgb_model=XGBClassifier(tree_method='exact')

In [55]:
xgb_model.fit(X_train, y_train.values.ravel())

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [111]:
with open('XGBPDModel.pkl', 'wb') as file:
    pickle.dump(xgb_model, file)

In [56]:
xgb_model.score(X_train, y_train.values.ravel())

0.965008930143637

In [57]:
y_pred_xgb=xgb_model.predict(X_test)

In [61]:
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95      4995
           1       0.98      0.91      0.94      4944

    accuracy                           0.95      9939
   macro avg       0.95      0.95      0.95      9939
weighted avg       0.95      0.95      0.95      9939

In [67]:
feature_imp_xgb=pd.DataFrame({'features':balanced_features.columns, 'coeff_xgb':xgb_model.feature_importances_})
feature_importance_mapping2(xgb_model, balanced_features)

                      features     coeff
8                          OWN  0.176669
5          loan_percent_income  0.119503
9                         RENT  0.118584
14                     VENTURE  0.092268
11             HOMEIMPROVEMENT  0.073652
4                loan_int_rate  0.071382
6   cb_person_cred_hist_length  0.067474
2            person_emp_length  0.057173
10                   EDUCATION  0.053881
13                    PERSONAL  0.041223
0                   person_age  0.038770
1                person_income  0.036838
15   cb_person_default_on_file  0.019395
12                     MEDICAL  0.015802
7                        OTHER  0.008806
3                    loan_amnt  0.008579

In [69]:
feature_imp=pd.concat([feature_imp_logit, feature_imp_rf, feature_imp_xgb], axis=1)
feature_imp

,features,coeff_logit,features,coeff_rr,features,coeff_xgb
0,person_age,-0.081021,person_age,0.061891,person_age,0.038770
1,person_income,0.057039,person_income,0.152256,person_income,0.036838
2,person_emp_length,-0.031978,person_emp_length,0.074098,person_emp_length,0.057173
3,loan_amnt,-0.665658,loan_amnt,0.081368,loan_amnt,0.008579
4,loan_int_rate,0.989437,loan_int_rate,0.206094,loan_int_rate,0.071382
5,loan_percent_income,1.395252,loan_percent_income,0.206761,loan_percent_income,0.119503
6,cb_person_cred_hist_length,0.021204,cb_person_cred_hist_length,0.057276,cb_person_cred_hist_length,0.067474
7,OTHER,-0.833533,OTHER,0.000423,OTHER,0.008806
8,OWN,-2.129313,OWN,0.019812,OWN,0.176669
9,RENT,0.464900,RENT,0.051025,RENT,0.118584
10,EDUCATION,-1.246159,EDUCATION,0.015288,EDUCATION,0.053881
11,HOMEIMPROVEMENT,-0.308789,HOMEIMPROVEMENT,0.017837,HOMEIMPROVEMENT,0.073652
12,MEDICAL,-0.556714,MEDICAL,0.008611,MEDICAL,0.015802
13,PERSONAL,-0.985018,PERSONAL,0.013159,PERSONAL,0.041223
14,VENTURE,-1.527150,VENTURE,0.017365,VENTURE,0.092268
15,cb_person_default_on_file,0.066307,cb_person_default_on_file,0.016735,cb_person_default_on_file,0.019395

#### Merging with original test data

In [76]:
xgb_prediction_df = pd.DataFrame({'test_indices_xgb': X_test.index, 'xgb_pred': y_pred_xgb})
logit_prediction_df = pd.DataFrame({'test_indices_logit': X_test.index, 'logit_pred': y_pred_logit})
rf_prediction_df = pd.DataFrame({'test_indices_rf': X_test.index, 'rf_pred': y_pred_rf})

In [77]:
rf_prediction_df.head()

   test_indices_rf  rf_pred
0            24808        0
1             9935        0
2            14054        0
3              147        0
4             4070        1

In [81]:
merged_with_orig = cr_data.merge(xgb_prediction_df, left_index=True, right_on='test_indices_xgb', how='left')
merged_with_rf = merged_with_orig.merge(rf_prediction_df, left_index=True, right_on='test_indices_rf', how='left')
merged_final = merged_with_rf.merge(logit_prediction_df, left_index=True, right_on='test_indices_logit', how='left')
merged_final.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,test_indices_xgb,xgb_pred,test_indices_rf,rf_pred,test_indices_logit,logit_pred
NaN,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0,NaN,NaN,NaN,NaN,NaN
NaN,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,1,1.0,9831.0,NaN,NaN,NaN
NaN,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,2,NaN,NaN,NaN,NaN,NaN
NaN,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,3,NaN,NaN,NaN,NaN,NaN
NaN,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2,4,1.0,442.0,NaN,NaN,NaN

In [88]:
merged_final.shape

(273, 18)

In [84]:
merged_final.dropna(inplace=True)

In [93]:
final_data_with_pred = merged_final.drop(['test_indices_rf', 'test_indices_logit', 'test_indices_xgb'], axis=1)
final_data_with_pred.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,xgb_pred,rf_pred,logit_pred
7782.0,24,78956,RENT,5.0,MEDICAL,B,35000,11.11,1,0.44,N,4,1.0,0.0,1.0
7968.0,25,12600,OWN,3.0,PERSONAL,C,1750,13.61,0,0.14,N,3,0.0,1.0,0.0
9251.0,22,153000,MORTGAGE,5.0,DEBTCONSOLIDATION,D,24000,15.62,1,0.16,Y,2,1.0,1.0,0.0
5662.0,22,16094,MORTGAGE,2.0,VENTURE,A,5500,7.14,1,0.34,N,3,1.0,0.0,1.0
143.0,21,18000,OWN,1.0,PERSONAL,B,2500,11.36,0,0.14,N,3,0.0,1.0,0.0

In [98]:
# pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [99]:
final_data_with_pred.to_excel(r"C:\Users\dwipa\Desktop\pd_model_development\output\pd_predictions.xlsx", index=False)

In [100]:
print(classification_report(final_data_with_pred['loan_status'], final_data_with_pred['xgb_pred']))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95       210
           1       0.92      0.73      0.81        63

    accuracy                           0.92       273
   macro avg       0.92      0.86      0.88       273
weighted avg       0.92      0.92      0.92       273

In [102]:
from sklearn.metrics import confusion_matrix

In [103]:
confusion_matrix(final_data_with_pred['loan_status'], final_data_with_pred['xgb_pred'])

array([[206,   4],
       [ 17,  46]])